# This is a YAML file.
# Please use two-space tabs instead of the \t character.

server:
  bind: 127.0.0.1     # Address to bind to.
  port: 9000          # Port for listening to.
  type: fcgi          # Types are "fcgi" for a FastCGI server and "standalone" for a simple HTTP server.

hosts:
  default: "./default"
# beta.example.org: /home/users/projects/beta.example.org

